version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/vanna-workflow
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
  test:
    docker:
      - image: circleci/node:8-browsers
    working_directory: ~/vanna-workflow
    steps:
      - checkout
      - run:
          name: Sanity check 
          command: ls -la
      - run:
          name: Test
          command: ./node_modules/.bin/jest

workflows:
  version: 2
  build_test:
    jobs:
      - build
      - test:
          requires:
            - build